---
driver_plugin: docker

platforms:
- name: ubuntu



platforms:
  - name: ubuntu-12.04
    driver_config:
      run_list:
      - recipe[apt]
      forward:
        - 22:2222
        - 80:8080
        - 443:8443
      provision_command: echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
  - name: centos-6.4
    driver_config:
      image: centos
      platform: rhel
      run_list:
      - recipe[yum]
      forward:
        - 22:2222
        - 80:8081
        - 443:8444

suites:
  - name: default
    run_list:
      - recipe[magento::default]
    attributes:
      mysql:
        server_debian_password: test
        server_root_password: test
        server_repl_password: test
      magento:
        db:
          password: magento
